language: ruby
branches:
  only:
    - develop
    - master
rvm:
  - 1.8.7
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - sudo apt-get install `cut -d " " -f 1 config/packages | egrep -v "(^#|wkhtml|bundler)"` 
before_script:
  - psql -c 'create database foi_test template template0 encoding sql_ascii;' -U postgres
  - co database.yml database.yml-test
