language: ruby
branches:
  only:
    - travistest
rvm:
  - 1.8.7
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -y install exim4-daemon-light
  - sudo apt-get -y install `cut -d " " -f 1 config/packages | egrep -v "(^#|wkhtml|bundler)"` 
before_script:
  - cp database.yml database.yml-test
