language: ruby
branches:
  only:
    - travistest
rvm:
  - 1.8.7
before_install:
  - git submodule update --init --recursive
  - psql -c "create database foi_test template template0 encoding 'SQL_ASCII';" -U postgres
  - cp config/database.yml-test config/database.yml
  - sudo apt-get update
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -y install exim4-daemon-light
  - sudo apt-get -y install `cut -d " " -f 1 config/packages | egrep -v "(^#|wkhtml|bundler)"` 
before_script:
