sq:
  about: 
  admin: 
  all-authorities: 
  annotate: 
  api: 
  attach: 
  banned: 
  blog: 
  body: 
  c: 
  categorise: 
  censor: 
  change_email: 
  change_password: 
  clarification: 
  clear_photo: 
  clear_profile_photo: 
  contact: 
  create: 
  css: 
  csv: 
  custom: 
  debug: 
  delete_all_type: 
  describe: 
  destroy: 
  destroy_incoming: 
  destroy_outgoing: 
  destroy_track: 
  details: 
  download_raw_email: 
  draft_photo: 
  due_date: 
  edit: 
  edit_comment: 
  edit_outgoing: 
  feed: 
  generate_upload_url: 
  help: 
  html: 
  import_csv: 
  list: 
  local: 
  login_as: 
  missing_scheme: 
  move_request: 
  new: 
  officers: 
  photo: 
  play: 
  png: 
  privacy: 
  profile: 
  random: 
  recent: 
  redeliver_incoming: 
  request: 
  request_event: 
  requesting: 
  resend: 
  response: 
  river: 
  search: 
  set_about_me: 
  set_photo: 
  show: 
  show_raw_email: 
  sign_in: 
  sign_out: 
  sign_up: 
  similar: 
  stats: 
  stop: 
  successful: 
  test: 
  timeline: 
  track: 
  unclassified: 
  unhappy: 
  update: 
  update_comment: 
  update_outgoing: 
  upload: 
  user: 
  view_email: 
